gisaia/ARLAS-d3

src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts
src/donuts/MultiSelectionDonut.ts
src/donuts/OneSelectionDonut.ts
src/donuts/style/donut.style.css
src/donuts/utils/DonutUtils.ts
src/index.ts
tslint.json

externalize donut implementation from arlas-web-components

---

src/donuts/AbstractDonut.ts

recalculate donut container dimensions on resize window event

---

package.json
src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts
src/donuts/utils/DonutUtils.ts
src/index.ts
src/utils/color-generator.ts
yarn.lock

Add an interface that propose a function to set donut nodes colors

---

src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts

Translate Y axes so that they're not hidden by histogram

---

src/histograms/AbstractHistogram.ts
src/histograms/HistogramParams.ts

Histograms : Display only selections containing data

---

src/histograms/AbstractHistogram.ts
src/histograms/utils/HistogramUtils.ts

Fix date locale : use utc

---

src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts
src/histograms/utils/HistogramUtils.ts

Adjust precision of tooltip xContent & xTicks to datainterval precision

---

src/histograms/AbstractHistogram.ts
src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/swimlanes/SwimlaneBars.ts
src/histograms/swimlanes/SwimlaneCircles.ts

Fix bug of thin bars in swimlane

---

src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts

Fix donut : each node take its own size not the sum of leaf nodes

---

src/index.ts

Fix : export missing classes

---

src/donuts/AbstractDonut.ts

Fix checking of existence of size in donuts nodes

---

src/histograms/AbstractHistogram.ts
src/histograms/utils/HistogramUtils.ts

Histogram : fix date undefined when one bucket is represented

---

src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts
src/donuts/utils/DonutUtils.ts
src/utils/color-generator.ts

- Possibility to specify a keysToColors list
- Possibility to specify a colorsSaturationWeight
- ColorGenerator getColor method generates a color from a key, a keysToColors list and a colorsSaturationWeight
Fix #72

Enhance colorizing donut arcs

---

src/gauge/Gauge.ts
src/index.ts

Implement gauge component

---

src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts

Handle no-data values in histograms

---

src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts

Fix bug related to [ticksDateFormat] option

---

src/histograms/charts/AbstractChart.ts

Remove forcing brush visibility to true

---

package-lock.json
package-release.json
package.json
yarn.lock

Upgrade rxjs to 6.5.3 and remove rxjs-compat

---

src/histograms/AbstractHistogram.ts
src/histograms/HistogramParams.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts
src/histograms/charts/ChartOneDimension.ts
src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/swimlanes/SwimlaneBars.ts
src/histograms/swimlanes/SwimlaneCircles.ts
src/histograms/utils/HistogramUtils.ts
src/index.ts

- fix #100 - Separate swimlane data and histogram data
- fix #101 - Add a new representation of colors => column oriented
- fix #102 - Add a legend for colors

Swimlane enhacements

---

src/histograms/charts/AbstractChart.ts

[Histogram] fix plotting charts that have the same bucket value

---

src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts

[Donut] add an input to configure donuts diameters

---

package-lock.json
src/histograms/charts/ChartBars.ts

Add a custom style for min/max values of a bar histogram

---

package-lock.json
src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts

Handle negative values in bar & area charts

---

package-lock.json
src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts

Fix bug related to when charts y axis don't start from zero

---

package-lock.json
src/donuts/AbstractDonut.ts
src/donuts/DonutParams.ts
src/donuts/MultiSelectionDonut.ts
src/donuts/utils/DonutUtils.ts
src/index.ts

Enhance donut tooltip 

---

src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/swimlanes/SwimlaneBars.ts
src/histograms/utils/HistogramUtils.ts

Revert "Fix infinity values in swimlane"

---

package-lock.json
src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/swimlanes/SwimlaneBars.ts
src/histograms/utils/HistogramUtils.ts

Fix infinity values in swimlane

---

src/histograms/utils/HistogramUtils.ts

Fix number formatting for number lower than 1

---

src/histograms/charts/AbstractChart.ts

Fix displayed temporal tooltip

---

src/calendar-timeline/lib/classes/axes/axis.ts
src/calendar-timeline/lib/classes/axes/day.axis.ts
src/calendar-timeline/lib/classes/axes/week.axis.ts
src/calendar-timeline/lib/classes/buckets/buckets.ts
src/calendar-timeline/lib/classes/buckets/circle.buckets.ts
src/calendar-timeline/lib/classes/drawable.object.ts
src/calendar-timeline/timeline.ts
src/index.ts
test/app.js
test/index.html
test/package-lock.json

Draw day axis

---

src/calendar-timeline/lib/classes/buckets/buckets.ts
src/calendar-timeline/lib/classes/cursor/cursor.ts
src/calendar-timeline/lib/classes/cursor/vertical.line.ts
src/calendar-timeline/lib/classes/drawable.object.ts
src/calendar-timeline/lib/classes/temporal.object.ts
src/calendar-timeline/timeline.ts
test/app.js

Add click action on cursor + display vertical line

---

src/calendar-timeline/lib/classes/axes/axis.ts
src/calendar-timeline/lib/classes/axes/month.axis.ts
src/calendar-timeline/lib/classes/axes/season.axis.ts
src/calendar-timeline/lib/classes/axes/week.axis.ts
src/calendar-timeline/lib/classes/axes/year.axis.ts
src/calendar-timeline/lib/classes/buckets/band.buckets.ts
src/calendar-timeline/lib/classes/cursor/cursor.ts
src/calendar-timeline/lib/classes/season.ts
src/calendar-timeline/lib/classes/temporal.object.ts
src/calendar-timeline/timeline.ts
test/app.js

Add season granularity
Add year granularity
Improve display of month granularity

[Timeline] Years and seasons

---

src/calendar-timeline/lib/classes/axes/axis.ts
src/calendar-timeline/lib/classes/axes/week.axis.ts

Homegenize font's size + apply uppercase

---

src/histograms/charts/AbstractChart.ts
src/histograms/utils/HistogramUtils.ts

fix: filter on histogram too sensitive

---

src/histograms/utils/HistogramUtils.ts

fix: negative tick values are displayed as NaN

---

src/histograms/HistogramParams.ts
src/histograms/brushes/brush.ts
src/histograms/brushes/rectangle-brush.ts
src/histograms/brushes/slider-brush.ts
src/histograms/charts/AbstractChart.ts
src/histograms/utils/HistogramUtils.ts
src/styles/histogram.style.css
test/app.css
test/app.js

The brush looks like this : 
While brushing, the circles get bigger ans the stroke thicker

histograms: add a new brush type : slider

---

src/histograms/charts/AbstractChart.ts

Part of the fix to gisaia/ARLAS-wui#513

fix: no update of the brush when the brush is in use

---

src/histograms/AbstractHistogram.ts
src/histograms/brushes/brush.ts
src/histograms/brushes/rectangle-brush.ts
src/histograms/brushes/slider-brush.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts
src/histograms/charts/ChartCurve.ts
src/histograms/utils/HistogramUtils.ts
test/app.js
test/index.html

fix: display xaxis ticks with selection exceeding the data

---

src/histograms/charts/AbstractChart.ts

Unshift older/lower extended values to the data domain in x-axis

---

src/histograms/charts/AbstractChart.ts

This reverts commit d5e460232c8daa9f591499a3e791475879119e90.

Revert "fix: no update of the brush when the brush is in use"

---

src/histograms/AbstractHistogram.ts
src/histograms/HistogramParams.ts
src/histograms/buckets/buckets.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartCurve.ts
src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/utils/HistogramUtils.ts
src/index.ts
test/app.js

feat: emits the bucket's x start/end values on hover

---

src/histograms/AbstractHistogram.ts
src/histograms/charts/AbstractChart.ts
src/histograms/charts/ChartArea.ts
src/histograms/charts/ChartBars.ts
src/histograms/charts/ChartCurve.ts
src/histograms/charts/ChartOneDimension.ts
src/histograms/swimlanes/AbstractSwimlane.ts
src/histograms/swimlanes/SwimlaneBars.ts
src/histograms/swimlanes/SwimlaneCircles.ts
src/histograms/utils/HistogramUtils.ts
test/app.js

Fix x domain to plot data

---

src/donuts/AbstractDonut.ts
src/donuts/utils/DonutUtils.ts
src/index.ts

- Fix gisaia/ARLAS-wui#986
Side changes:
- Increase thickness of stroke by default to better separate colors for better readability

fix: add donut arc when no data is present
